name: Outdated dependencies

on:
  push:
  schedule:
    - cron: '0 21 * * *'

jobs:
  antq:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
      - uses: liquidz/antq-action@main
        with:
          excludes: 'org.clojure/tools.deps.alpha lambdaisland/deep-diff2'
