name: Test

on:
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          persist-credentials: false
          fetch-depth: 0
          fetch-tags: true

      - name: Prepare java
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Typos
        uses: crate-ci/typos@v1.36.2

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@13.4
        with:
          cli: 1.12.2.1565
          clj-kondo: 2025.07.28

      - name: Lint
        run: npm run lint

      - name: Install packages
        run: npm ci

      - name: Test
        run: npm run test
